language: node_js
node_js: '10.6'
cache:
  yarn: true
git:
  depth: 1
env:
  - REPO_NAME=digital-drifter/vue-hotel-datepicker
  - DEPLOY_BRANCH=release
stages:
  - lint
  - test
  - name: bundle
    if: branch = "$DEPLOY_BRANCH"
before_install:
  - curl -o - -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile --non-interactive
jobs:
  include:
  - stage: lint
    script:
      - yarn lint
  - stage: test
    before_script:
      - yarn global add codecov
    script:
      - yarn test:unit
  - stage: bundle
    script:
      - yarn bundle
before_deploy:
  - git config --local user.name "$GIT_USERNAME"
  - git config --local user.email "$GIT_EMAIL"
  - export VERSION=$(npx -c 'echo "$npm_package_version"')
  - git tag "v$VERSION"
deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key:
      secure: "$GITHUB_API_KEY"
    file: "dist/vue-hotel-datepicker.*"
    on:
      branch: "$DEPLOY_BRANCH"
      tags: true
      repo: "$REPO_NAME"
  - provider: npm
    skip_cleanup: true
    email: "$GIT_EMAIL"
    api_key:
      secure: "$NPM_API_KEY"
    on:
      branch: "$DEPLOY_BRANCH"
      tags: true
      repo: "$REPO_NAME"
